name = "zacharologist-chase-api"
main = "src/index.js"
compatibility_date = "2026-06-04"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "zacharologist-chase-db"
database_id = "1ac719e5-fca1-43fb-903f-bd90a2d85528"


[[r2_buckets]]
binding = "RADAR_BUCKET"
bucket_name = "zacharologist-radar"
[[durable_objects.bindings]]
name = "LIVE_ALERT_HUB"
class_name = "LiveAlertHub"

[[migrations]]
tag = "live_alert_hub_v1"
new_sqlite_classes = ["LiveAlertHub"]

[[routes]]
pattern = "zacharologistwx.com/api/*"
zone_name = "zacharologistwx.com"