name = "zacharologist-chase-api"
main = "src/index.js"
compatibility_date = "2026-06-04"

[[d1_databases]]
binding = "DB"
database_name = "zacharologist-chase-db"
database_id = "1ac719e5-fca1-43fb-903f-bd90a2d85528"


[[r2_buckets]]
binding = "RADAR_BUCKET"
bucket_name = "zacharologist-radar"